version: "3"


services:
  web_demo:
    restart: always
    build:
      context: ./frontend
      args:
        HOST_IP: ${HOST_IP}
    ports:
      - "8050:80"
    volumes:
      - ${PWD}/frontend/index.html:/var/www/html/index.html
    env_file:
      - .env
    depends_on:
      - chatbot
      - chatbot_actions

  chatbot:
    restart: always
    build:
      context: ./chatbot
    ports:
      - "5006:5005"
    volumes:
      - ./chatbot:/app

  chatbot_actions:
    restart: always
    build:
      context: ./chatbot/actions
    ports:
      - "5056:5055"
    volumes:
      - ./chatbot/actions:/app/actions
      - ./chatbot/data:/app/data

  reverse_proxy:
    container_name: reverse_proxy
    restart: always
    image: nginx:alpine
    ports:
      - '8080:8080'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chatbot
      - chatbot_actions
      - web_demo