name: Deploy chatbot on server

on:
  push:
    branches:
      - "main"

jobs:

  build:
    name: redeploy
    runs-on: ubuntu-latest
    steps:
    - name: Copy project and run docker compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: cd ~/vse-fis-chatbot  && 
          echo "Updating project" && 
          /usr/bin/git checkout main && 
          /usr/bin/git pull https://${{ secrets.PAT }}@github.com/tsai00/vse-fis-chatbot.git && 
          /usr/bin/git reset --hard HEAD && 
          echo "Creating .env file" && 
          cp .env.sample .env && 
          sed -i "s|\*\*\*\*|${{ secrets.HOST }}|g" ./.env && 
          echo "Running docker compose down" && 
          docker compose down && 
          echo "Running docker compose up" && 
          docker compose up --build -d
